app:
  version_check_url: "https://raw.githubusercontent.com/sansan0/TrendRadar/refs/heads/master/version"
  show_version_update: true # æ§åˆ¶æ˜¾ç¤ºç‰ˆæœ¬æ›´æ–°æç¤ºï¼Œæ”¹æˆ false å°†ä¸æ¥å—æ–°ç‰ˆæœ¬æç¤º

crawler:
  request_interval: 1000 # è¯·æ±‚é—´éš”(æ¯«ç§’)
  enable_crawler: true # æ˜¯å¦å¯ç”¨çˆ¬å–æ–°é—»åŠŸèƒ½ï¼Œfalse æ—¶ç›´æ¥åœæ­¢ç¨‹åº
  use_proxy: false # æ˜¯å¦å¯ç”¨ä»£ç†ï¼Œfalse æ—¶ä¸ºå…³é—­
  default_proxy: "http://127.0.0.1:10086"

# ğŸ”¸ dailyï¼ˆå½“æ—¥æ±‡æ€»æ¨¡å¼ï¼‰
#   â€¢ æ¨é€æ—¶æœºï¼šæŒ‰æ—¶æ¨é€
#   â€¢ æ˜¾ç¤ºå†…å®¹ï¼šå½“æ—¥æ‰€æœ‰åŒ¹é…æ–°é—» + æ–°å¢æ–°é—»åŒºåŸŸ
#   â€¢ é€‚ç”¨åœºæ™¯ï¼šæ—¥æŠ¥æ€»ç»“ã€å…¨é¢äº†è§£å½“æ—¥çƒ­ç‚¹è¶‹åŠ¿
#
# ğŸ”¸ currentï¼ˆå½“å‰æ¦œå•æ¨¡å¼ï¼‰
#   â€¢ æ¨é€æ—¶æœºï¼šæŒ‰æ—¶æ¨é€
#   â€¢ æ˜¾ç¤ºå†…å®¹ï¼šå½“å‰æ¦œå•åŒ¹é…æ–°é—» + æ–°å¢æ–°é—»åŒºåŸŸ
#   â€¢ é€‚ç”¨åœºæ™¯ï¼šå®æ—¶çƒ­ç‚¹è¿½è¸ªã€äº†è§£å½“å‰æœ€ç«çš„å†…å®¹
#
# ğŸ”¸ incrementalï¼ˆå¢é‡ç›‘æ§æ¨¡å¼ï¼‰
#   â€¢ æ¨é€æ—¶æœºï¼šæœ‰æ–°å¢æ‰æ¨é€
#   â€¢ æ˜¾ç¤ºå†…å®¹ï¼šæ–°å‡ºç°çš„åŒ¹é…é¢‘ç‡è¯æ–°é—»
#   â€¢ é€‚ç”¨åœºæ™¯ï¼šé¿å…é‡å¤ä¿¡æ¯å¹²æ‰°

report:
  mode: "current" # å¯é€‰: "daily"|"incremental"|"current"
  rank_threshold: 5 # æ’åé«˜äº®é˜ˆå€¼

notification:
  enable_notification: true # æ˜¯å¦å¯ç”¨é€šçŸ¥åŠŸèƒ½ï¼Œfalse æ—¶ä¸å‘é€æ‰‹æœºé€šçŸ¥
  message_batch_size: 4000 # æ¶ˆæ¯åˆ†æ‰¹å¤§å°ï¼ˆå­—èŠ‚ï¼‰(è¿™ä¸ªé…ç½®åˆ«åŠ¨)
  batch_send_interval: 1 # æ‰¹æ¬¡å‘é€é—´éš”ï¼ˆç§’ï¼‰
  feishu_message_separator: "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”" # feishu æ¶ˆæ¯åˆ†å‰²çº¿

  webhooks:
    feishu_url: "" # é£ä¹¦æœºå™¨äººçš„ webhook URL
    dingtalk_url: "" # é’‰é’‰æœºå™¨äººçš„ webhook URL
    wework_url: "" # ä¼ä¸šå¾®ä¿¡æœºå™¨äººçš„ webhook URL
    telegram_bot_token: "" # Telegram Bot Token
    telegram_chat_id: "" # Telegram Chat ID

# ç”¨äºè®©å…³æ³¨åº¦æ›´é«˜çš„æ–°é—»åœ¨æ›´å‰é¢æ˜¾ç¤ºï¼Œåˆèµ·æ¥æ˜¯ 1 å°±è¡Œ
weight:
  rank_weight: 0.6 # æ’åæƒé‡
  frequency_weight: 0.3 # é¢‘æ¬¡æƒé‡
  hotness_weight: 0.1 # çƒ­åº¦æƒé‡

# å¢åŠ æ— èŠçš„å°çŸ¥è¯†
# è¿™é‡Œçš„ name ä½ å¯ä»¥å®šä¹‰ä»»æ„åç§°ï¼Œåªå…·æœ‰æ˜¾ç¤ºä½œç”¨ï¼Œä¸ä¼šå½±å“æ•°æ®çš„å¤„ç†
platforms:
  - id: "36kr"
    name: "36æ°ª"
  - id: "aifadian"
    name: "çˆ±å‘ç”µ"
  - id: "baidu"
    name: "ç™¾åº¦çƒ­æœ"
  - id: "bilibili-hot-searc"
    name: "å“”å“©å“”å“©"
  - id: "cankaoxiaoxi"
    name: "å‚è€ƒæ¶ˆæ¯"
  - id: "chongbuluo"
    name: "è™«éƒ¨è½"
  - id: "cnblogs"
    name: "åšå®¢å›­"
  - id: "cnbeta"
    name: "CNBETA"
  - id: "douban"
    name: "è±†ç“£"
  - id: "douyin"
    name: "æŠ–éŸ³"
  - id: "eastmoney"
    name: "ä¸œæ–¹è´¢å¯Œç½‘"
  - id: "fastbull"
    name: "å¿«ç‰›è´¢ç»"
  - id: "ifeng"
    name: "å‡¤å‡°ç½‘"
  - id: "gelonghui"
    name: "æ ¼éš†æ±‡"
  - id: "ghxi"
    name: "æ¸¯è‚¡ä¾ "
  - id: "github-trending"
    name: "GitHubè¶‹åŠ¿"
  - id: "hackernews"
    name: "é»‘å®¢æ–°é—»ï¼ˆHacker Newsï¼‰"
  - id: "hexun"
    name: "å’Œè®¯ç½‘"
  - id: "hupu"
    name: "è™æ‰‘"
  - id: "huoxing24"
    name: "ç«æ˜Ÿè´¢ç»"
  - id: "ithome"
    name: "ITä¹‹å®¶"
  - id: "jijinba"
    name: "åŸºé‡‘å§"
  - id: "jin10"
    name: "é‡‘åæ•°æ®"
  - id: "juejin"
    name: "ç¨€åœŸæ˜é‡‘"
  - id: "kaopu"
    name: "é è°±"
  - id: "kanshou"
    name: "å¿«çœ‹"
  - id: "kuaishou"
    name: "å¿«æ‰‹"
  - id: "leiphone"
    name: "é›·é”‹ç½‘"
  - id: "linuxdo"
    name: "Linuxä¸­å›½"
  - id: "lofter"
    name: "LOFTER"
  - id: "mktnews"
    name: "å¸‚åœºæ–°é—»"
  - id: "netease"
    name: "ç½‘æ˜“æ–°é—»"
  - id: "nowcoder"
    name: "ç‰›å®¢ç½‘"
  - id: "pcbeta"
    name: "ç”µè„‘çˆ±å¥½è€…"
  - id: "pingwest"
    name: "å“ç©"
  - id: "producthunt"
    name: "äº§å“çŒäººï¼ˆProductHuntï¼‰"
  - id: "qq"
    name: "è…¾è®¯æ–°é—»"
  - id: "reddit"
    name: "Reddit"
  - id: "sina"
    name: "æ–°æµªæ–°é—»"
  - id: "smzdm"
    name: "ä»€ä¹ˆå€¼å¾—ä¹°"
  - id: "solidot"
    name: "Solidotå¥‡å®¢èµ„è®¯"
  - id: "sohu"
    name: "æœç‹æ–°é—»"
  - id: "sputniknewscn"
    name: "ä¿„ç½—æ–¯å«æ˜Ÿé€šè®¯ç¤¾ä¸­æ–‡ç½‘"
  - id: "sspai"
    name: "å°‘æ•°æ´¾"
  - id: "thepaper"
    name: "æ¾æ¹ƒæ–°é—»"
  - id: "tieba"
    name: "ç™¾åº¦è´´å§"
  - id: "toutiao"
    name: "ä»Šæ—¥å¤´æ¡"
  - id: "tuchong"
    name: "å›¾è™«"
  - id: "twitter"
    name: "Twitterï¼ˆç°Xå¹³å°ï¼‰"
  - id: "v2ex"
    name: "V2EX"
  - id: "wechat"
    name: "å¾®ä¿¡å…¬ä¼—å·"
  - id: "weibo"
    name: "å¾®åš"
  - id: "wallstreetcn-hot"
    name: "åå°”è¡—è§é—»"
  - id: "wangyi"
    name: "ç½‘æ˜“"
  - id: "xiaohongshu"
    name: "å°çº¢ä¹¦"
  - id: "xinhua"
    name: "æ–°åç½‘"
  - id: "xueqiu"
    name: "é›ªçƒ"
  - id: "yicai"
    name: "ç¬¬ä¸€è´¢ç»"
  - id: "zaobao"
    name: "è”åˆæ—©æŠ¥"
  - id: "zhihu"
    name: "çŸ¥ä¹"
  - id: "zhongguojingji"
    name: "ä¸­å›½ç»æµç½‘"
